src/components/SplashSection.vue, src/styles/colors.scss
See description in comments for colors.scss
We'll add to these colors as the designers give us more to work with.
=> Added SCSS Color Variables File

src/components/RegistrationPage.vue
This could be part of the single page design or a seperate page
=> Added a template for a registration page

build/webpack.base.conf.js, package.json
Make sure this works, it builds for me but you know
=> Adding JQuery

src/components/RegistrationPage.vue, src/components/SplashSection.vue, src/components/TerminalCheckbox.vue, src/components/TerminalInput.vue, src/styles/vars.scss
Created a vars scss file to contain commonly used fonts and other variables
=> Refactor widely used variables to Vars

index.html, package-lock.json, package.json, src/components/MapSection.vue
It was because of the async defer import, so now I use a proper npm require
=> Fixed "google not found" import issues

src/components/MapSection.vue
It was being "greedy" so I made it "cooperative"
=> Fixed stupid Map cooperative scrolling

src/components/MapSection.vue
Marker Screenshot: https://i.imgur.com/sBPNLyf.png
Made map smaller on mobile.
=> Map Updates

src/components/AboutSection.vue, src/components/HomePage.vue
Added the old FAQ content and restyled the section. also added a new unscoped scss for <a>
=> Added Q's and A's and <a> link styling

src/components/FooterSection.vue
This can be moved or restyled but we need it so
=> Added a footer and MLH Code of Conduct

src/components/MLHTrustBadge.vue
oopsmybad
also i moved the style to the style tag while i was at it
=> Fixed a blue box behind the badge from new <a> styles

src/components/AboutSection.vue, src/components/ScheduleSection.vue, src/components/SplashSection.vue, src/components/SponsorsSection.vue
needed less legroom from earlier changes
=> Sponsors now play nice

src/components/ScheduleSection.vue
=> Fixed font sizes for mobile in schedule

build/webpack.prod.conf.js, package-lock.json, package.json
When we push this, we'll need to restart the dameon process to restart the express server with compression.
=> Added gzip compression

src/components/ScheduleSection.vue
https://www.youtube.com/watch?v=gw1G5yBwPT0
=> Removed prelim warning

src/components/SplashSection.vue
on really tiny devices (iPhone 5) the date goes onto a new line, this fixes that
=> Fix to squished date on smaller devices

src/components/SponsorsSection.vue
=> Waiting on microstrategy to pay

src/components/SponsorsSection.vue
=> Added MicroStrategy to Sponsors

src/components/SponsorsSection.vue
Also changed the organization to use Vue better
=> Should fix the sizing/centering of sponsors

src/components/HomePage.vue, src/components/Navigation.vue, src/components/RegistrationSection.vue, src/components/TravelSection.vue, src/components/VolunteerSection.vue, src/styles/colors.scss, src/styles/eightbit-btn.scss, src/styles/headers.scss
Moved them to lower on the page as they are less important but still good to have
=> Added Travel Section

src/components/DetailsSection.vue, src/components/MapSection.vue, src/components/RegistrationSection.vue, src/components/TravelSection.vue, src/components/VolunteerSection.vue, src/styles/info-term.scss
Also moved info-term to scss file for easy imports :)
=> Added location info and Minors form note
